CC = riscv64-unknown-elf-gcc
LD = riscv64-unknown-elf-ld
OBJCOPY = riscv64-unknown-elf-objcopy

CCFLAGS = -c -g -ffreestanding -march=rv64ima_zicsr -mabi=lp64 -mcmodel=medany -fno-pie -std=gnu99 -I include

HART_NUM = 4

QEMU = qemu-system-riscv64
