CC      = riscv32-unknown-elf-gcc
LD      = riscv32-unknown-elf-ld
OBJCOPY = riscv32-unknown-elf-objcopy

CCFLAGS = -c -ffreestanding -fno-pie -std=gnu99 -I . -mcmodel=medany

NHART   = 4

QEMU    = qemu-system-riscv32
